# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 240a91ef9faa1a199cf1e4c06544e6e0cb5414f9dc23c64e9d717bcebae694cffb37950358967c61365eeeb56b06f26cd6843c6a8d56d491f8c1a78e3ea20661

test:
  secret_key_base: 8a31f0193c66f56c65d30899059c53ec2858ef4fbcab42e147da0ed2eb1dee1612b5dc6740688686d8601ebb2385978829b5dc6d34271e35787db8e3f5e9520a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
